# Generated by Django 4.1.7 on 2023-02-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_fecha_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_reg',
            field=models.CharField(max_length=30),
        ),
    ]
